apiVersion: v1
kind: Service
metadata:
  name: sample-fastapi
  labels:
    {{- include "sample-fastapi.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.fastapi.service.type }}
  selector:
    app.kubernetes.io/name: sample-fastapi
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: {{ .Values.fastapi.service.port }}
      targetPort: http
