apiVersion: "{{ .Values.karpenter_modulename }}/v1"
kind: EC2NodeClass
metadata:
  name: worker-nodepool
spec:
  amiFamily: AL2023
  amiSelectorTerms:
    - alias: al2023@latest
  role: "karpenter-node-role-{{ .Values.eks_name }}"  # Terraform에서 만든 이름
  subnetSelectorTerms:
    - tags:
        "{{ .Values.karpenter_tag }}": "{{ .Values.eks_name }}"
  securityGroupSelectorTerms:
    - tags:
        "{{ .Values.karpenter_tag }}": "{{ .Values.eks_name }}"
  tags:
    Environment: "prod"
    ManagedBy: "karpenter"
    Name: "eks-worker-node"