# 기본 애플리케이션 설정
replicaCount: 3
images:
  frontend: "372666940978.dkr.ecr.ap-northeast-2.amazonaws.com/mak_frontend_ecr:1.2"
  userservice: "372666940978.dkr.ecr.ap-northeast-2.amazonaws.com/mak_userservice_ecr:1.2"
  contacts: "372666940978.dkr.ecr.ap-northeast-2.amazonaws.com/mak_contacts_ecr:1.2"
  balancereader: "372666940978.dkr.ecr.ap-northeast-2.amazonaws.com/mak_balancereader_ecr:0.9"
  ledgerwriter: "372666940978.dkr.ecr.ap-northeast-2.amazonaws.com/mak_ledgerwriter_ecr:1.2"
  transactionhistory: "372666940978.dkr.ecr.ap-northeast-2.amazonaws.com/mak_transactionhistory_ecr:0.9"

image:
  pullPolicy: IfNotPresent
# 💡 패턴 분석 결과에 따라 깃허브 액션이 변경할 자원 권장값 영역
resources:
  requests:
    cpu: "200m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"
service:
  type: ClusterIP
  port: 80
# Redis 연결 설정
redis:
  host: "redis" # K8s 내 Redis 서비스 이름 (또는 AWS ElastiCache 엔드포인트)
  port: 6379
  db: 0
  password: "redis" # Redis 비밀번호
  tlsEnabled: false # 로컬/K8s 내부는 false, ElastiCache TLS 사용 시 true
secrets:
  jwtPrivateKey: ""
  jwtPublicKey: ""
components:
  backend: true
  frontend: "372666940978.dkr.ecr.ap-northeast-2.amazonaws.com/mak_frontend_ecr:1.2"