# 기본 애플리케이션 설정
replicaCount: 3
image:
  repository: us-central1-docker.pkg.dev/bank-of-anthos-ci/bank-of-anthos/frontend
  tag: "v0.6.10"
  pullPolicy: IfNotPresent
# 💡 패턴 분석 결과에 따라 깃허브 액션이 변경할 자원 권장값 영역
resources:
  requests:
    cpu: "200m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"
service:
  type: ClusterIP
  port: 80
# Redis 연결 설정
redis:
  host: "redis" # K8s 내 Redis 서비스 이름 (또는 AWS ElastiCache 엔드포인트)
  port: 6379
  db: 0
  password: "redis" # Redis 비밀번호
  tlsEnabled: false # 로컬/K8s 내부는 false, ElastiCache TLS 사용 시 true
