{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tg-gateway.fullname" . }}-secret
  labels:
    {{- include "tg-gateway.labels" . | nindent 4 }}
type: Opaque
stringData:
  TELEGRAM_BOT_TOKEN: {{ .Values.secrets.telegramBotToken | quote }}
  TELEGRAM_CHAT_ID: {{ .Values.secrets.telegramChatId | quote }}
  GITOPS_TOKEN: {{ .Values.secrets.gitopsToken | quote }}
{{- end }}
