apiVersion: v1
kind: ConfigMap
metadata:
  name: environment-config
  namespace: {{ .Release.Namespace | default "default" }}
data:
  LOCAL_ROUTING_NUM: "883745000"
  PUB_KEY_PATH: "/etc/jwt/jwtcert.pem"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ledger-db-config
  namespace: {{ .Release.Namespace | default "default" }}
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://ledger-db:5432/postgres"
  SPRING_DATASOURCE_USERNAME: "postgres"
  SPRING_DATASOURCE_PASSWORD: "password"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: service-api-config
  namespace: {{ .Release.Namespace | default "default" }}
data:
  BALANCES_API_ADDR: "balancereader:8080"