apiVersion: v1
kind: ConfigMap
metadata:
  name: environment-config
  namespace: {{ .Release.Namespace | default "default" }}
data:
  LOCAL_ROUTING_NUM: "883745000"
  PUB_KEY_PATH: "/tmp/.ssh/publickey"
  ENABLE_TRACING: "false"
  DISABLE_TRACING: "1"
  DISABLE_PROFILER: "1"
  ENABLE_METRICS: "false"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: service-api-config
  namespace: {{ .Release.Namespace | default "default" }}
data:
  TRANSACTIONS_API_ADDR: "ledgerwriter:8080"
  BALANCES_API_ADDR: "balancereader:8080"
  HISTORY_API_ADDR: "transactionhistory:8080"
  CONTACTS_API_ADDR: "contacts:8080"
  USERSERVICE_API_ADDR: "userservice:8080"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-data-config
  namespace: {{ .Release.Namespace | default "default" }}
data:
  USE_DEMO_DATA: "True"
  DEMO_LOGIN_USERNAME: "testuser"
  DEMO_LOGIN_PASSWORD: "bankofanthos"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: accounts-db-config
  namespace: {{ .Release.Namespace | default "default" }}
data:
  ACCOUNTS_DB_URI: postgresql://accounts-admin:accounts-pwd@accounts-db:5432/accounts-db
  POSTGRES_DB: accounts-db
  POSTGRES_PASSWORD: accounts-pwd
  POSTGRES_USER: accounts-admin
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ledger-db-config
  namespace: {{ .Release.Namespace | default "default" }}
data:
  POSTGRES_DB: postgresdb
  POSTGRES_PASSWORD: password
  POSTGRES_USER: admin
  SPRING_DATASOURCE_PASSWORD: password
  SPRING_DATASOURCE_URL: jdbc:postgresql://ledger-db:5432/postgresdb
  SPRING_DATASOURCE_USERNAME: admin
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bank-of-anthos
  namespace: {{ .Release.Namespace | default "default" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: {{ .Release.Namespace | default "default" }}
type: Opaque
stringData:
  REDIS_PASSWORD: {{ .Values.redis.password | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-key
  namespace: {{ .Release.Namespace | default "default" }}
type: Opaque
stringData:
  jwtRS256.key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpAIBAAKCAQEAtVnzgcTKn6pHNsika6xDdPp3M8OugJ6R/XHuRnKJ4QYp776B
    M+2l9odPFcOsrx15q/HpG8xzqRNkdJxr/ZkhpCvDdXVxOD7fKQqPYEZjWiPHQoxt
    TVjat3JRbQD0t13sBo9jOuB0U7INpcGxHhPrZrRWlxrnDDfVx1nXwpIBnphXH0zA
    BhkSPZQ67lLcVApR8/pDzBRcKxmXz1lBtb+Wo6H3RxQYNwKpjPZlO8vc5T9H53dz
    OnAxQPVTmqOSDubYDMwnj/UuMdBXxFbfgMjlJtv0tS53Tkf7HE/Itw+F7WeM6+ay
    m/QBppvcptFcS1+RbLyCy6g0/yBzu3xTYIapxwIDAQABAoIBAAsbfUyfbwGkfkQe
    ueNWY7NQe+iRvahnDe4GAmASN9uucvcaJfO2RIn6858Town+tisP4AUx2ouqgmaa
    Bgs8S9EwVQJmtQ6K20Q6P1nYNdGZi2TKEQ/Bt3Ow7sfMXTC18fTc52j9wmI175wN
    Zvm+opZhyUPsA+a9rLxPBmYGZ079Tyw65wV0HcqgoYlV5C8z5UW8WH/9PqLyG7gj
    lIaFTrdHuVANBpsG6/g4O1TqZstYkKjQofPQ7JtLBrvneNYUJYwM5GTp1rCcKpKH
    DD0MCk1DCYWNQDyjMVD4uJf1DULlNbH9q/NCUx+Da3vYmr6wwwWyMqcLuC3PG97e
    EqJ3GuECgYEA6j725i3Qqmqvk6M9m+PXSiwdBeUj98c0H42HZ9Cy+lPfzpsW3C+m
    WjQx6rmucclnq7lpOzKodVRagZvJjEsNXxWsDiTkwQRHwcUGZpQ1KqgVQ2ChvOPR
    kTOuCm+uuRsaf6Ne4wTO94VykHUY8YB2rGaqLm5CypHRC+jLs7xm1PkCgYEAxjF0
    Yk3xNQKSPlGf7tydYTgivlPCLYexALlBKbygHHck+Z5yahJ85mzH0tRnav9Pozwh
    r4T7XcaeAeV0kfmdSoX1FdvvKQkgTJwaFe+/hVmSmdKmopIKYPgw4tfrPtuVFPzN
    13B6eeB1ADgXqXdkxHfmLH0iHezIF3c81jMg5L8CgYBnviUZAld08jT6fQSPIxQ5
    PFpKPxZz6VyTUNoUR2DM7xKi7Rrtv4i8UHt/CmdQ67MnYcFSP3hOJmLDHhzgLmko
    oG+IABzzwxKIpdrU2XTGhJSON6DKCFfLKAk/hADs6C0PNGqUvo9vHkID6mh2pL9q
    UTmzwI+CKZxc2uhEnP8p+QKBgQCN1prKN6mmHF75BoWE9pITH4+N0nenCfMc53fB
    HOMhPAtUMZcEXpLQfY1MTwJsSqd91OzupicW56vxA3u3dIKi8NeDe1Dfd06MRTNN
    +7R/BKmsOFtVAVs4Jqcl0QzkgVViHcJaqn6cdoyFSZ91gqK1EHHD6RHfhLN2R7lc
    Ol8SFQKBgQC6KzOUiB6I8JxXUIhxgn9OQMeczMDg9xJVwLP2ZyD0EFPDnT8kqDhC
    LEF0/Lu7GuTOAvWVh5UOK9TNYkgQBf0o8h5hSwMYHQm2iSGESG4WS4AcBs9Gluqm
    T9CSCSSP0xlwU88M4445b+/TxHltPjQffASqnKE8ojpyVupeooAa0w==
    -----END RSA PRIVATE KEY-----
  jwtRS256.key.pub: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtVnzgcTKn6pHNsika6xD
    dPp3M8OugJ6R/XHuRnKJ4QYp776BM+2l9odPFcOsrx15q/HpG8xzqRNkdJxr/Zkh
    pCvDdXVxOD7fKQqPYEZjWiPHQoxtTVjat3JRbQD0t13sBo9jOuB0U7INpcGxHhPr
    ZrRWlxrnDDfVx1nXwpIBnphXH0zABhkSPZQ67lLcVApR8/pDzBRcKxmXz1lBtb+W
    o6H3RxQYNwKpjPZlO8vc5T9H53dzOnAxQPVTmqOSDubYDMwnj/UuMdBXxFbfgMjl
    Jtv0tS53Tkf7HE/Itw+F7WeM6+aym/QBppvcptFcS1+RbLyCy6g0/yBzu3xTYIap
    xwIDAQAB
    -----END PUBLIC KEY-----