apiVersion: v1
kind: ConfigMap
metadata:
  name: environment-config
  namespace: {{ .Release.Namespace | default "default" }}
data:
  LOCAL_ROUTING_NUM: "883745000"
  PUB_KEY_PATH: "/tmp/.ssh/publickey"
  ENABLE_TRACING: "false"
  DISABLE_TRACING: "1"
  DISABLE_PROFILER: "1"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: service-api-config
  namespace: {{ .Release.Namespace | default "default" }}
data:
  TRANSACTIONS_API_ADDR: "ledgerwriter:8080"
  BALANCES_API_ADDR: "balancereader:8080"
  HISTORY_API_ADDR: "transactionhistory:8080"
  CONTACTS_API_ADDR: "contacts:8080"
  USERSERVICE_API_ADDR: "userservice:8080"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-data-config
  namespace: {{ .Release.Namespace | default "default" }}
data:
  USE_DEMO_DATA: "True"
  DEMO_LOGIN_USERNAME: "testuser"
  DEMO_LOGIN_PASSWORD: "bankofanthos"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: accounts-db-config
  namespace: {{ .Release.Namespace | default "default" }}
data:
  ACCOUNTS_DB_URI: postgresql://accounts-admin:accounts-pwd@accounts-db:5432/accounts-db
  POSTGRES_DB: accounts-db
  POSTGRES_PASSWORD: accounts-pwd
  POSTGRES_USER: accounts-admin
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ledger-db-config
  namespace: {{ .Release.Namespace | default "default" }}
data:
  POSTGRES_DB: postgresdb
  POSTGRES_PASSWORD: password
  POSTGRES_USER: admin
  SPRING_DATASOURCE_PASSWORD: password
  SPRING_DATASOURCE_URL: jdbc:postgresql://ledger-db:5432/postgresdb
  SPRING_DATASOURCE_USERNAME: admin
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bank-of-anthos
  namespace: {{ .Release.Namespace | default "default" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: {{ .Release.Namespace | default "default" }}
type: Opaque
stringData:
  REDIS_PASSWORD: {{ .Values.redis.password | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-key
  namespace: {{ .Release.Namespace | default "default" }}
type: Opaque
stringData:
  jwtRS256.key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEowIBAAKCAQEAxbzicqntDf5KIMeiYj9Z9xjIagv+ufsykb8gmBgX89e9vhR8
    c80JjbpQtcGxNk9YiJrZKjQzq8DrZWubno61yOdF8ub52q8rr1sC6VprPzw4Ha6D
    qef+wE87288auJywzt2u9mOBY2kkkAdH5by2k74nin8vlxJOw1pEjKAJ52BrfP2p
    dtAk/hLP2koWwx5Sw28gs8Z5tnag01z8eDNqktw4+gwKX02mM0uzmjyfN03Uxx5s
    GaEJYw5s4kVsR+ieVHyCAL4b9YdEivRU1gOwrLJaN9URB7Rp7rdlrige8UU9tZB4
    FjO2/hNwC2cRgXtwbVNcQDZ0dPcwZZecQIDAQABAoGBAKboriWw72q8whcgwS9m
    O59ov9XuWmO3fYfa8yF10+omcBpvIr27Wo1yxAKLd3E5e8CX2pjkGpi8etaTzPgs
    pq6ZdqxjQEmeWFghrygqj1MmlpogU1b4eggZnty3bd9FYpCzzMnysw5dTuA44GB9
    E4N/bGZU4euzkU+tVjwNxTAkEAE5eTbvbWtbDtAn1rUicv28wjLeoRkIEjVNGk5p
    bXtvfkngbh0r5vos35NJXnS2vgf7m4gp2rY8OYfuyeSfmfEwQJBAMojPczaalvaG
    y4B8xisvRLlpnk+MbRG0imbQp904Ul4Cw9w4m0rXCvoXDKse8hr60mFkb+p5ixk1
    J+wVTeuvuccQQCrC3SLjkL3kgnvXvtyQDG6BAoHiwU5uMdvNynvsrYi8bAvfk/hY
    6d+z+po2c9nrJajdLd2d4JYgR7bm+WLKj8BAkE0tn+qdP8q7KvbvJnivZcxXQkk
    pzkA9A8vnfBTkben4sT/5feNFu49eZBddKy9r1Eow2wwq0PUgJJ0r7neu/cFCQI
    0JmvEvRtA69tt4hHB2h728AdgPdtTywqsKIrmyfvFkXcub9WC3Lo1d4NR0Jgi9fy
    jMlRGCoxcxkC3b+Ha32dij9CQQefwy/qgaIJX2soux7c+oPc1p1IeroM8R9kox/o
    vkoFeDKOvJmZgPHEWEPCbIenmZRijGFt4Lg/JWF+Rvo8BJnpnRk=
    -----END RSA PRIVATE KEY-----
  jwtRS256.key.pub: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxbzicqntDf5KIMeiYj9Z
    9xjIagv+ufsykb8gmBgX89e9vhR8c80JjbpQtcGxNk9YiJrZKjQzq8DrZWubno61
    yOdF8ub52q8rr1sC6VprPzw4Ha6Dqef+wE87288auJywzt2u9mOBY2kkkAdH5by2
    k74nin8vlxJOw1pEjKAJ52BrfP2pdtAk/hLP2koWwx5Sw28gs8Z5tnag01z8eDNq
    ktw4+gwKX02mM0uzmjyfN03Uxx5sGaEJYw5s4kVsR+ieVHyCAL4b9YdEivRU1gOw
    rLJaN9URB7Rp7rdlrige8UU9tZB4FjO2/hNwC2cRgXtwbVNcQDZ0dPcwZZecQIDA
    QAB
    -----END PUBLIC KEY-----