{{- if .Values.components.frontend -}}
apiVersion: gateway.k8s.aws/v1beta1
kind: TargetGroupConfiguration
metadata:
  name: mak-app-active-tg-config
  namespace: {{ .Release.Namespace | default "default" }}
spec:
  targetReference:
    group: ""
    kind: Service
    name: mak-app-active
  defaultConfiguration:
    targetType: ip
    protocol: HTTP
    protocolVersion: HTTP1
    healthCheckConfig:
      healthCheckInterval: 15
      healthCheckTimeout: 5
      healthyThresholdCount: 2
      unhealthyThresholdCount: 2
      healthCheckPort: "8080"
      healthCheckPath: "/version"
      healthCheckProtocol: HTTP
---
apiVersion: gateway.k8s.aws/v1beta1
kind: TargetGroupConfiguration
metadata:
  name: mak-app-preview-tg-config
  namespace: {{ .Release.Namespace | default "default" }}
spec:
  targetReference:
    group: ""
    kind: Service
    name: mak-app-preview
  defaultConfiguration:
    targetType: ip
    protocol: HTTP
    protocolVersion: HTTP1
    healthCheckConfig:
      healthCheckInterval: 15
      healthCheckTimeout: 5
      healthyThresholdCount: 2
      unhealthyThresholdCount: 2
      healthCheckPort: "8080"
      healthCheckPath: "/version"
      healthCheckProtocol: HTTP
{{- end -}}