{{- if .Values.components.frontend -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: mak-app-route
  namespace: {{ .Release.Namespace | default "default" }}
spec:
  parentRefs:
    - name: my-gateway
      namespace: default
  hostnames:
    - "tuby.shop"
  rules:
    - backendRefs:
        - name: mak-app-active
          port: 80
          weight: 100
        - name: mak-app-preview
          port: 80
          weight: 0
---
apiVersion: v1
kind: Service
metadata:
  name: mak-app-active
  namespace: {{ .Release.Namespace | default "default" }}
  labels:
    app: frontend
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.service.port | default 80 }}
      targetPort: 8080
      protocol: TCP
  selector:
    app: frontend
---
apiVersion: v1
kind: Service
metadata:
  name: mak-app-preview
  namespace: {{ .Release.Namespace | default "default" }}
  labels:
    app: frontend
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: frontend
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: mak-app-rollout
  namespace: {{ .Release.Namespace | default "default" }}
spec:
  replicas: {{ .Values.replicaCount | default 3 }}
  selector:
    matchLabels:
      app: frontend
  strategy:
    canary:
      activeService: mak-app-active
      previewService: mak-app-preview
      trafficRouting:
        gateway:
          httpRouteName: mak-app-route
      steps:
        - setWeight: 10
        - pause: {}
        - setWeight: 50
        - pause: { duration: 300s }
  template:
    metadata:
      labels:
        app: frontend
        application: bank-of-anthos
        team: frontend
        tier: web
    spec:
      containers:
        - name: mak-container
          image: "{{ .Values.images.frontend }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "{{ .Values.resources.requests.cpu }}"
              memory: "{{ .Values.resources.requests.memory }}"
            limits:
              cpu: "{{ .Values.resources.limits.cpu }}"
              memory: "{{ .Values.resources.limits.memory }}"
          env:
            - name: PORT
              value: "8080"
            - name: ENABLE_TRACING
              value: "false"
            - name: ENABLE_PROMETHEUS
              value: "true"
            - name: LOG_LEVEL
              value: "info"
            - name: REDIS_HOST
              value: {{ .Values.redis.host | quote }}
            - name: REDIS_PORT
              value: {{ .Values.redis.port | quote }}
            - name: REDIS_DB
              value: {{ .Values.redis.db | quote }}
            - name: REDIS_TLS_ENABLED
              value: {{ .Values.redis.tlsEnabled | quote }}

            # === 외부 CNPG 데이터베이스 연동 계정 주입 ===
            # - name: DB_HOST
            #   value: "project03-db-rw.backend.svc.cluster.local"
            # - name: DB_PORT
            #   value: "5432"
            # - name: DB_USER
            #   valueFrom:
            #     secretKeyRef:
            #       name: project03-db-app
            #       key: username
            # - name: DB_PASSWORD
            #   valueFrom:
            #     secretKeyRef:
            #       name: project03-db-app
            #       key: password
            # ===
          envFrom:
            - configMapRef:
                name: environment-config
            - configMapRef:
                name: service-api-config
            # === 추가
            # - configMapRef:
            #     name: accounts-db-config
            # ===
          volumeMounts:
            - mountPath: /tmp
              name: tmp
            - mountPath: /tmp/.ssh
              name: publickey
              readOnly: true
      volumes:
        - emptyDir: {}
          name: tmp
        - name: publickey
          secret:
            secretName: jwt-key
            items:
              - key: jwtRS256.key.pub
                path: publickey
{{- end -}}