apiVersion: gateway.k8s.aws/v1beta1
kind: TargetGroupConfiguration
metadata:
  name: mak-app-active-tg-config
  namespace: {{ .Values.namespace.frontend | default "default" }}
spec:
  targetReference:
    group: ""
    kind: Service
    name: mak-app-active
  defaultConfiguration:
    targetType: ip
    protocol: HTTP
    protocolVersion: HTTP1
    healthCheck:
      enabled: true
      intervalSeconds: 15
      timeoutSeconds: 5
      healthyThresholdCount: 2
      unhealthyThresholdCount: 2
      port: "8080"
      path: "/version"
      protocol: HTTP
---
apiVersion: gateway.k8s.aws/v1beta1
kind: TargetGroupConfiguration
metadata:
  name: mak-app-preview-tg-config
  namespace: {{ .Values.namespace.frontend | default "default" }}
spec:
  targetReference:
    group: ""
    kind: Service
    name: mak-app-preview
  defaultConfiguration:
    targetType: ip
    protocol: HTTP
    protocolVersion: HTTP1
    healthCheck:
      enabled: true
      intervalSeconds: 15
      timeoutSeconds: 5
      healthyThresholdCount: 2
      unhealthyThresholdCount: 2
      port: "8080"
      path: "/version"
      protocol: HTTP