{{- if .Values.components.frontend -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgen
  namespace: {{ .Release.Namespace | default "default" }}
  labels:
    app: loadgen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loadgen
  template:
    metadata:
      labels:
        app: loadgen
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      terminationGracePeriodSeconds: 5
      restartPolicy: Always
      containers:
        - name: main
          image: docker.io/yoonhakim/locust-tasks:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: LOCUST_USERS
              value: "800"
            - name: LOCUST_SPAWN_RATE
              value: "50"
            - name: LOCUST_HOST
              value: http://frontend
            - name: LOCUST_HEADLESS
              value: "true"
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 2000m
              memory: 1Gi
{{- end -}}
