apiVersion: apps/v1
kind: Deployment
metadata:
  name: balancereader
  namespace: {{ .Release.Namespace | default "default" }}
spec:
  selector:
    matchLabels:
      app: balancereader
  template:
    metadata:
      labels:
        app: balancereader
    spec:
      containers:
      - name: balancereader
        image: gcr.io/bank-of-anthos-ci/balancereader:v0.5.11
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_CLOUD_GCP_CORE_ENABLED
          value: "false"
        - name: SPRING_CLOUD_GCP_METRICS_ENABLED
          value: "false"
        - name: SPRING_CLOUD_GCP_TRACE_ENABLED
          value: "false"
        - name: PUB_KEY_PATH
          value: "/etc/jwt/jwtcert.pem"
        - name: LOCAL_ROUTING_NUM
          value: "883745000"
        - name: LEDGER_DB_ADDR
          value: "ledger-db:5432"
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://ledger-db:5432/postgres"
        - name: SPRING_DATASOURCE_USERNAME
          value: "postgres"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "password"
        - name: VERSION
          value: "v0.5.11"
        - name: PORT
          value: "8080"
        - name: ENABLE_TRACING
          value: "false"
        envFrom:
        - configMapRef:
            name: environment-config
        - configMapRef:
            name: ledger-db-config
        volumeMounts:
        - name: jwt-key-vol
          mountPath: "/etc/jwt"
          readOnly: true
      volumes:
      - name: jwt-key-vol
        secret:
          secretName: jwt-key
---
apiVersion: v1
kind: Service
metadata:
  name: balancereader
  namespace: {{ .Release.Namespace | default "default" }}
spec:
  type: ClusterIP
  selector:
    app: balancereader
  ports:
  - port: 8080
    targetPort: 8080