apiVersion: apps/v1
kind: Deployment
metadata:
  name: ledger-db
  namespace: {{ .Release.Namespace | default "default" }}
  labels:
    app: ledger-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ledger-db
  template:
    metadata:
      labels:
        app: ledger-db
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          env:
            - name: POSTGRES_DB
              value: "postgres"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "password"
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: init-script
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: init-script
          configMap:
            name: ledger-db-init-script
---
apiVersion: v1
kind: Service
metadata:
  name: ledger-db
  namespace: {{ .Release.Namespace | default "default" }}
spec:
  type: ClusterIP
  selector:
    app: ledger-db
  ports:
    - port: 5432
      targetPort: 5432