apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: mak-app-rollout
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: frontend
  strategy:
    canary:
      # 1. 블루그린의 격리 개념을 카나리에 이식합니다.
      activeService: mak-app-active     # 실 서비스 (Blue)
      previewService: mak-app-preview   # k6 부하 테스트 타겟 (Green)
      # ========================================================
      # AWS ALB Ingress 대신 K8s Gateway API 연동 설정
      # ========================================================
      trafficRouting:
        gateway:
          # 배포할 HTTPRoute 명세서의 이름
          httpRouteName: mak-app-route
      steps:
        # [Step 1] 신규 버전(Green)이 뜨면 일단 10%의 트래픽만 흘립니다.
        - setWeight: 10
        # [Step 2] 락(Pause)을 걸어 무기한 대기 상태로 만듭니다.
        #'mak-app-preview' 주소로 k6 스트레스 테스트를 강하게 쏴보면서 성능과 리소스 추이를 분석합니다!
        - pause: {}
        # [Step 3] 검증이 끝나 승인(Promote)하면 50%로 트래픽을 올려 안정성을 재검증합니다.
        - setWeight: 50
        - pause: { duration: 300s }  
        # [Step 4] 최종 100%로 전환되어 완전한 스위칭(Blue ➡️ Green)이 완료됩니다.
  template:
    metadata:
      labels:
        app: frontend
        application: bank-of-anthos
        team: frontend
        tier: web
    spec:
      containers:
        - name: mak-container
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          env:

            # KeyError 해결을 위한 트레이싱 옵션
            - name: ENABLE_TRACING
              value: "false"

            # [필수] 공개키 경로 설정 (TypeError 해결)
            - name: PUB_KEY_PATH
              value: "/etc/jwt/jwtcert.pem"
            
            # [필수] 마이크로서비스 및 외부 서비스 주소 설정
            # (설정 안 할 경우 기본 서비스명이 들어가나, 서비스가 없으면 에러가 날 수 있음)
            - name: ACCOUNT_DATABASE_SERVICE_ADDR
              value: "accounts-db:5432"
            - name: LEDGER_WRITER_SERVICE_ADDR
              value: "ledgerwriter:8080"
            - name: BALANCE_READER_SERVICE_ADDR
              value: "balancereader:8080"
            - name: TRANSACTION_HISTORY_SERVICE_ADDR
              value: "transactionhistory:8080"
            - name: CONTACTS_SERVICE_ADDR
              value: "contacts:8080"
            - name: USERSERVICE_SERVICE_ADDR
              value: "userservice:8080"
            - name: USERSERVICE_API_ADDR
              value: "userservice:8080"
            - name: USERSERVICE_URL
              value: "http://userservice:8080"
            - name: LOGIN_URI
              value: "http://userservice:8080/login"
            - name: ENV_PLATFORM
              value: "gcp"                 # 플랫폼 스타일 오류 방지


            #  프론트엔드 앱 실행에 필수적인 PORT 및 프로메테우스 설정
            - name: PORT
              value: "8080"
            - name: ENABLE_PROMETHEUS
              value: "true"
            - name: LOG_LEVEL
              value: "info"

            # 1. 일반 접속 정보 (values.yaml 매핑)
            - name: REDIS_HOST
              value: {{ .Values.redis.host | quote }}
            - name: REDIS_PORT
              value: {{ .Values.redis.port | quote }}
            - name: REDIS_DB
              value: {{ .Values.redis.db | quote }}
            - name: REDIS_TLS_ENABLED
              value: {{ .Values.redis.tlsEnabled | quote }}

            # 2. 비밀번호 (Secret 참조)
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret       
                  key: REDIS_PASSWORD    

          # 💡 [추가] ConfigMap 볼륨 마운트
          volumeMounts:
            - name: jwt-key-vol
              mountPath: "/etc/jwt"
              readOnly: true

      # 💡 [추가] 볼륨 정의
      volumes:
        - name: jwt-key-vol
          configMap:
            name: jwt-public-key
          
          resources:
            requests:
              cpu: "{{ .Values.resources.requests.cpu }}"     
              memory: "{{ .Values.resources.requests.memory }}" 
            limits:
              cpu: "{{ .Values.resources.limits.cpu }}"      
              memory: "{{ .Values.resources.limits.memory }}"    