apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: default # 인프라 담당자와 싱크 맞춰야할 네임스페이스
type: Opaque
data:
  # 헬름이 배포될 때 values.yaml의 평문 패스워드를 자동으로 Base64 암호화하여 K8s에 등록합니다.
  redis-password: {{ .Values.redis.password | b64enc | quote }}