apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: default # 인프라 담당자와 싱크 맞춰야할 네임스페이스
type: Opaque
stringData:
  # stringData를 사용하면 b64enc 없이 평문 그대로 써도 K8s가 자동 암호화
  REDIS_PASSWORD: {{ .Values.redis.password | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-key
  namespace: default
type: Opaque
stringData:
  # userservice가 기본으로 찾는 파일명(jwtkey.pem, jwtcert.pem)으로 직접 키 생성
  jwtkey.pem: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEowIBAAKCAQEA0Z5
    -----END RSA PRIVATE KEY-----
  jwtcert.pem: |
    -----BEGIN PUBLIC KEY-----
    MFwwDQYJKoZIhvcNAQE
    -----END PUBLIC KEY-----
