apiVersion: v1
kind: Service
metadata:
  name: mak-app-active
  labels:
    app: mak-app
spec:
  type: {{ .Values.service.type }}      # ClusterIP
  ports:
    - port: {{ .Values.service.port }}  # 서비스가 외부(또는 다른 팟)로부터 받을 포트 (80)
      targetPort: 80                    # deployment.yaml에 정의된 컨테이너 내부 포트 (80)
      protocol: TCP
  selector:
    # matchLabels와 정확히 일치
    app: mak-app
---
# k6로 부하를 쏴서 성능을 검증할 신규 테스트 서비스 (Green)
apiVersion: v1
kind: Service
metadata:
  name: mak-app-preview # previewService와 이름 일치
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: mak-app