apiVersion: v1
kind: Service
metadata:
  name: mak-app
  labels:
    app: mak-app
spec:
  # values.yaml의 service.type (ClusterIP)을 동적으로 주입
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}      # 서비스가 외부(또는 다른 팟)로부터 받을 포트 (80)
      targetPort: 80                         # deployment.yaml에 정의된 컨테이너 내부 포트 (80)
      protocol: TCP
  selector:
    # Deployment의 matchLabels와 정확히 일치시켜서 팟들을 연결합니다.
    app: mak-app