# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: transactionhistory
#   namespace: {{ .Release.Namespace | default "default" }}
# spec:
#   selector:
#     matchLabels:
#       app: transactionhistory
#   template:
#     metadata:
#       labels:
#         app: transactionhistory
#     spec:
#       containers:
#       - name: transactionhistory
#         image: gcr.io/bank-of-anthos-ci/transactionhistory:v0.5.11
#         ports:
#         - containerPort: 8080
#         env:
#         - name: GOOGLE_APPLICATION_CREDENTIALS
#           value: "/etc/jwt/jwtcert.pem"
#         - name: GOOGLE_CLOUD_PROJECT
#           value: "test-project"
#         - name: GCP_PROJECT_ID
#           value: "test-project"
#         - name: VERSION
#           value: "v0.5.11"
#         - name: PORT
#           value: "8080"
#         - name: ENABLE_TRACING
#           value: "false"
#         - name: ENABLE_METRICS
#           value: "false"
#         - name: SPRING_CLOUD_GCP_CORE_ENABLED
#           value: "false"
#         - name: SPRING_CLOUD_GCP_LOGGING_ENABLED
#           value: "false"
#         - name: SPRING_CLOUD_GCP_METRICS_ENABLED
#           value: "false"
#         - name: SPRING_CLOUD_GCP_TRACE_ENABLED
#           value: "false"
#         - name: MANAGEMENT_TRACING_ENABLED
#           value: "false"
#         envFrom:
#         - configMapRef:
#             name: environment-config
#         - configMapRef:
#             name: ledger-db-config
#         volumeMounts:
#         - name: jwt-key-vol
#           mountPath: "/etc/jwt"
#           readOnly: true
#       volumes:
#       - name: jwt-key-vol
#         secret:
#           secretName: jwt-key
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: transactionhistory
#   namespace: {{ .Release.Namespace | default "default" }}
# spec:
#   type: ClusterIP
#   selector:
#     app: transactionhistory
#   ports:
#   - port: 8080
#     targetPort: 8080