apiVersion: apps/v1
kind: Deployment
metadata:
  name: userservice
  namespace: default
  labels:
    app: userservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userservice
  template:
    metadata:
      labels:
        app: userservice
    spec:
      containers:
        - name: userservice
          image: us-central1-docker.pkg.dev/bank-of-anthos-ci/bank-of-anthos/userservice:v0.6.10
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: ENABLE_TRACING    # 필수 환경변수
              value: "false"
            # DB 연결 관련 환경변수 풀세트
            - name: ACCOUNT_DATABASE_SERVICE_ADDR
              value: "accounts-db:5432"
            - name: DB_HOST
              value: "accounts-db"
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASS
              value: "password"
            - name: DB_NAME
              value: "postgres"
            - name: DB_DATABASE
              value: "postgres"
            - name: TOKEN_EXPIRY_SECONDS
              value: "86400"
            - name: PRIV_KEY_PATH
              value: "/etc/jwt/jwtkey.pem"
            - name: PUB_KEY_PATH
              value: "/etc/jwt/jwtcert.pem"
          volumeMounts:
            - name: jwt-key-vol
              mountPath: "/etc/jwt"
              readOnly: true
      volumes:
        - name: jwt-key-vol
          secret:
            secretName: jwt-key
---
apiVersion: v1
kind: Service
metadata:
  name: userservice
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: userservice
  ports:
    - port: 8080
      targetPort: 8080