{{- range .Values.httpRoutes }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
spec:
  parentRefs:
    - name: {{ $.Values.gatewayName | default "my-gateway" }}
      namespace: {{ $.Values.gatewayNamespace | default "default" }}
      sectionName: https
  hostnames:
    - {{ .hostname | quote }}
  rules:
    - backendRefs:
        - name: {{ .serviceName }}
          port: {{ .port }}
{{- end }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: public-http-to-https
  namespace: default
spec:
  parentRefs:
    - name: {{ .Values.gatewayName | default "my-gateway" }}
      namespace: {{ .Values.gatewayNamespace | default "default" }}
      sectionName: http
  hostnames:
    {{- range .Values.httpRoutes }}
    - {{ .hostname | quote }}
    {{- end }}
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
