{{- range .Values.httpRoutes }}
---
apiVersion: gateway.k8s.aws/v1beta1
kind: TargetGroupConfiguration
metadata:
  name: {{ .name }}-tg-config
  namespace: {{ .namespace }}
spec:
  targetReference:
    group: ""
    kind: Service
    name: {{ .serviceName }}
  defaultConfiguration:
    targetType: ip           
    protocol: HTTP
    protocolVersion: HTTP1
{{- end }}
