apiVersion: v1
kind: Secret
metadata:
  name: thanos-objstore-config
  namespace: prometheus
type: Opaque
stringData:
  objstore.yml: |-
    type: s3
    config:
      bucket: project03-thanos-metrics-83154bf5
      endpoint: s3.ap-northeast-2.amazonaws.com
      region: ap-northeast-2
