name: Deploy Workflow

on:
  workflow_dispatch:
    inputs:
      target_tag:
        description: 'Target tag to deploy'
        required: false
        default: 'v1.2.0'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Execute Deploy
        run: |
          echo "🚀 Target Tag: ${{ github.event.inputs.target_tag }} 버전 배포 진행"