name: Custom Rollback Workflow

on:
  repository_dispatch:
    types: [rollback-custom, rollback_custom, deploy-custom]

jobs:
  rollback:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v3

      - name: Triggered Event Log
        run: |
          echo "🚀 Telegram / FastAPI에서 웹후크 신호를 수신했습니다!"
          echo "Payload: ${{ toJson(github.event.client_payload) }}"